name: Flask Security Pipeline Day4

on:
  push:
    branches:
      - main

jobs:
  sast_scans:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          cd day4
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bandit (Python SAST)
        run: |
          cd day4
          pip install bandit
          bandit -r . -f html -o bandit-report.html || true
        shell: bash
        continue-on-error: true

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: day4/bandit-report.html

      - name: Run Semgrep (Default Behavior)
        run: |
          cd day4
          pip install semgrep
          semgrep --config=auto --json --output=semgrep-report.json || true
        shell: bash
        continue-on-error: true

      - name: Upload Semgrep Json Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-json-report
          path: day4/semgrep-report.json

  trivy_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Trivy File System Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          format: json
          output: day4/trivy-report.json
          ignore-unfixed: true
          vuln-type: "os,library"
        continue-on-error: true

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: day4/trivy-report.json

  dast_scan:
    runs-on: ubuntu-latest
    needs: [sast_scans, trivy_scan]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          cd day4
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask App
        run: |
          cd day4
          nohup python vulnerable-app.py --host=0.0.0.0 --port=5000 > app.log 2>&1 &
          echo "Waiting for app to start..."
          for i in {1..10}; do
            curl --fail http://localhost:5000 && break
            echo "Waiting for Flask..."
            sleep 3
          done
        shell: bash

      - name: Show logs on failure
        if: failure()
        run: |
          cd day4
          echo "--- App failed to start. Displaying logs from app.log: ---"
          cat app.log

      - name: Fix permissions on workspace
        run: |
          sudo chown -R 1000:1000 ${{ github.workspace }}
          sudo chmod -R u+rwX ${{ github.workspace }}

      - name: Run ZAP Baseline Scan via Docker
        continue-on-error: true
        run: |
          docker run --rm \
            --user 1000:1000 \
            --add-host=host.docker.internal:host-gateway \
            -v ${{ github.workspace }}/day4:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://host.docker.internal:5000/ \
            -J zap-report.json \
            -w zap-report.md \
            -r zap-report.html || true

      - name: Upload ZAP DAST Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-reports
          path: |
            day4/zap-report.html
            day4/zap-report.md
            day4/zap-report.json
