name: Security Scanning Pipeline

on:
  push:
    branches: [ main ]

jobs:
  security-scans:
    runs-on: ubuntu-latest

    container:
      image: python:3.10-slim 

    steps:
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y curl git gcc build-essential

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install bandit semgrep

          # Install gitleaks manually (latest version)
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64.tar.gz | tar -xz -C /usr/local/bin gitleaks

      - name: Run Bandit
        run: |
          bandit -r . -f html -o bandit-report.html || true
        continue-on-error: true

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.html

      - name: Run Semgrep
        run: |
          semgrep --config=auto --json > semgrep-report.json || true
        continue-on-error: true

      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-report.json

      - name: Run Gitleaks
        run: |
          gitleaks detect --source . --report-path=gitleaks-report.json --report-format=json || true
        continue-on-error: true

      - name: Upload Gitleaks Report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json

      - name: Start Flask App
        run: |
          pip install gunicorn
          nohup gunicorn -b 127.0.0.1:5000 app_vulnerable:app &
          # Wait until the app is up
          for i in {1..30}; do
            if curl -sSf http://127.0.0.1:5000/ >/dev/null; then
              echo "App is up"
              break
            fi
            echo "Waiting for app... ($i)"
            sleep 1
          done

      - name: Run ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: "http://127.0.0.1:5000"
          fail_action: false
          artifact_name: zap-report
          cmd_options: "-r zap-report.html"

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html
