name: OWASP ZAP Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run ZAP Baseline Scan
        continue-on-error: true
        run: |
          sudo chown 1000:1000 ${{ github.workspace }}
          docker run --rm -v ${{ github.workspace }}:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t https://juice-shop.herokuapp.com/ \
            -g gen.conf \
            -J report_json.json \
            -w report_md.md \
            -r report_html.html
      - name: List generated reports
        run: ls -lh ${{ github.workspace }}

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zapscan
          path: |
            ${{ github.workspace }}/report_json.json
            ${{ github.workspace }}/report_md.md
            ${{ github.workspace }}/report_html.html
