name: OWASP ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Juice Shop
        run: |
          docker run -d --name juice-shop -p 3000:3000 bkimminich/juice-shop
          
      - name: Wait for Juice Shop to be ready
        run: |
          echo "Waiting for Juice Shop..."
          for i in {1..30}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Juice Shop is up!"
              break
            fi
            echo "Retrying in 5s..."
            sleep 5
          done
          
      - name: Run OWASP ZAP Baseline Scan
        run: |
          mkdir -p zap-reports
          chmod 777 zap-reports
          docker run --network host \
            -v "$(pwd)/zap-reports:/zap/wrk" \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://localhost:3000 \
            -r zap-report.html || true
            
      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-security-reports
          path: |
            zap-reports/
            zap-workspace/
         
